# Canonical packages: curl, git, zsh, tmux, bat, fzf, eza, nvim

debian_packages=(curl git zsh tmux bat fzf eza fonts-powerline build-essential procps file)
rhel_packages=(curl git zsh tmux bat fzf eza powerline-fonts @development-tools procps-ng file)
brew_packages=(neovim)
preflight_commands=(curl zsh tmux batcat fzf eza git nvim)
preflight_paths=("$HOME/.oh-my-zsh")
preflight_powerline_font=1